AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  UserService:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: org.t34.App::handleRequest
      Timeout: 60
      MemorySize: 512 
      Events:
        Login:
          Type: Api
          Properties:
            Path: '/user/login'
            Method: post
        Create:
          Type: Api
          Properties:
            Path: '/user/create'
            Method: post
        Update:
          Type: Api
          Properties:
            Path: '/user/update'
            Method: post
        View:
          Type: Api
          Properties:
            Path: '/user/view'
            Method: post
