name: PR Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test UserService
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: 'maven'
      - name: Test with maven
        working-directory: ./UserService
        run: mvn test
      - name: Check dependencies
        working-directory: ./UserService
        run: mvn dependency-check:check